### ISSUE TITLE
ros_jetson_stats in a Docker container

### ISSUE THREAD

**Issue by swaroophs** [rbonghi/ros_jetson_stats#5]
Hi!

Thanks for this awesome project! I have been trying to get this package running inside a Docker container on an AGX Xavier without much success. Here is what I have done:

1. Create a `Dockerfile` similar to the following
```
FROM ros:melodic-ros-core

RUN apt-get update && \
    apt-get install -y --no-install-recommends screen \
    git \
    g++ \
    python-pip \
    python3-setuptools \
    python3-pip \
    ros-melodic-diagnostics \
    make && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install wheel 
RUN pip install jetson-stats
RUN pip3 install wheel
RUN pip3 install jetson-stats

WORKDIR /home/test_ws
RUN git clone https://github.com/rbonghi/ros_jetson_stats.git src/ros_jetson_stats

RUN /ros_entrypoint.sh catkin_make && sed -i '$isource "/home/test_ws/devel/setup.bash"' /ros_entrypoint.sh

ENTRYPOINT ["/ros_entrypoint.sh"]
```
2. Build the docker image

`docker build -t  ros:jetson_stats .`

3. Run the docker container using the following

```
docker run -it \
--rm \
--network=host \
--name=ros_jtop \
-v "/run/jtop.sock:/run/jtop.sock" \
ros:jetson_stats \
roslaunch ros_jetson_stats jetson_stats.launch
```
4. I get the following error about `Authentication mismatch`:
```
... logging to /root/.ros/log/398e3672-4369-11eb-9adf-48b02d134584/roslaunch-xavier-1.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://127.0.0.1:36507/

SUMMARY
========

CLEAR PARAMETERS
 * /diagnostic_aggregator/

PARAMETERS
 * /diagnostic_aggregator/analyzers/jtop/analyzers/board/contains: board
 * /diagnostic_aggregator/analyzers/jtop/analyzers/board/path: board
 * /diagnostic_aggregator/analyzers/jtop/analyzers/board/remove_prefix: jetson_stats board
 * /diagnostic_aggregator/analyzers/jtop/analyzers/board/type: diagnostic_aggreg...
 * /diagnostic_aggregator/analyzers/jtop/analyzers/cpu/contains: cpu
 * /diagnostic_aggregator/analyzers/jtop/analyzers/cpu/path: CPU
 * /diagnostic_aggregator/analyzers/jtop/analyzers/cpu/remove_prefix: jetson_stats cpu
 * /diagnostic_aggregator/analyzers/jtop/analyzers/cpu/type: diagnostic_aggreg...
 * /diagnostic_aggregator/analyzers/jtop/analyzers/gpu/contains: gpu
 * /diagnostic_aggregator/analyzers/jtop/analyzers/gpu/path: GPU
 * /diagnostic_aggregator/analyzers/jtop/analyzers/gpu/remove_prefix: jetson_stats
 * /diagnostic_aggregator/analyzers/jtop/analyzers/gpu/type: diagnostic_aggreg...
 * /diagnostic_aggregator/analyzers/jtop/analyzers/memory/contains: mem
 * /diagnostic_aggregator/analyzers/jtop/analyzers/memory/path: Memory
 * /diagnostic_aggregator/analyzers/jtop/analyzers/memory/remove_prefix: jetson_stats mem
 * /diagnostic_aggregator/analyzers/jtop/analyzers/memory/type: diagnostic_aggreg...
 * /diagnostic_aggregator/analyzers/jtop/analyzers/power/contains: power
 * /diagnostic_aggregator/analyzers/jtop/analyzers/power/path: Power
 * /diagnostic_aggregator/analyzers/jtop/analyzers/power/remove_prefix: jetson_stats
 * /diagnostic_aggregator/analyzers/jtop/analyzers/power/type: diagnostic_aggreg...
 * /diagnostic_aggregator/analyzers/jtop/analyzers/temperatures/contains: temp
 * /diagnostic_aggregator/analyzers/jtop/analyzers/temperatures/path: Temperatures
 * /diagnostic_aggregator/analyzers/jtop/analyzers/temperatures/remove_prefix: jetson_stats
 * /diagnostic_aggregator/analyzers/jtop/analyzers/temperatures/type: diagnostic_aggreg...
 * /diagnostic_aggregator/analyzers/jtop/contains: jetson_stats
 * /diagnostic_aggregator/analyzers/jtop/path: jtop
 * /diagnostic_aggregator/analyzers/jtop/type: diagnostic_aggreg...
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /
    diagnostic_aggregator (diagnostic_aggregator/aggregator_node)
    ros_jetson_stats (ros_jetson_stats/jetson_stats.py)

auto-starting new master
process[master]: started with pid [63]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 398e3672-4369-11eb-9adf-48b02d134584
process[rosout-1]: started with pid [76]
started core service [/rosout]
process[ros_jetson_stats-2]: started with pid [84]
[INFO] [1608540484.532029]: {40: 1, 20: 0, 60: 2}
process[diagnostic_aggregator-3]: started with pid [85]
Traceback (most recent call last):
  File "/home/test_ws/src/ros_jetson_stats/scripts/jetson_stats.py", line 167, in <module>
    wrapper()
  File "/home/test_ws/src/ros_jetson_stats/scripts/jetson_stats.py", line 159, in wrapper
    jetson.start()
  File "/home/test_ws/src/ros_jetson_stats/scripts/jetson_stats.py", line 70, in start
    self.jetson.start()
  File "/usr/local/lib/python2.7/dist-packages/jtop/jtop.py", line 950, in start
    raise JtopException("Authentication mismatch with jetson-stats server")
jtop.core.exceptions.JtopException: Authentication mismatch with jetson-stats server
================================================================================REQUIRED process [ros_jetson_stats-2] has died!
process has died [pid 84, exit code 1, cmd /home/test_ws/src/ros_jetson_stats/scripts/jetson_stats.py __name:=ros_jetson_stats __log:=/root/.ros/log/398e3672-4369-11eb-9adf-48b02d134584/ros_jetson_stats-2.log].
log file: /root/.ros/log/398e3672-4369-11eb-9adf-48b02d134584/ros_jetson_stats-2*.log
Initiating shutdown!
================================================================================
[diagnostic_aggregator-3] killing on exit
[ros_jetson_stats-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```
5. However, with the same image, if I try to run `jtop`, I am able to see the correct output for `jtop`. The following is the run command I used for that successfully:
`docker run -it --rm --network=host --name=ros_jtop -v "/run/jtop.sock:/run/jtop.sock" ros:jetson_stats jtop`

Is there something additional that I need to do to get this package to work with ROS from a Docker container in addition to the volume mounting for `-v "/run/jtop.sock:/run/jtop.sock"`? Your help is much appreciated. 

FYI, my `jtop -v` returns `3.0.2` for both inside the Docker container and natively on the Xavier.

**Comment by swaroophs** [comment]
Actually got this to work. In my docker container, this error was seen when running with `python`. When I changed the `jetson_stats.py` in this repo to run in `python3`, it just worked. 

To clarify, changing the first line in `jetson_stats.py` from `#!/usr/bin/env python` to `#!/usr/bin/env python3` worked. I would also advice anyone trying this to make sure you have the same version of `jtop` running on both the host board and the container. In my case, `3.0.2` worked.
